In [8]:
myfile=sc.textFile("Users/mayam/Desktop/I699/inpc.csv")
myfile

Users/mayam/Desktop/I699/inpc.csv MapPartitionsRDD[15] at textFile at NativeMethodAccessorImpl.java:0

In [61]:
df=spark.read.csv("/Users/mayam/Desktop/I699/inpc.csv", header = "true")
df.head()

Row(person_id='1238', INDEX_AGE='53', GENDER='F', ETHNICITY='other', RACE='african_american', BIRTH_DATE='1950-10-06T00:00:00.000-06:00', diagRL='22.41', F_T2D_Diag='2001-04-07T00:00:00.000-05:00', F_GEST_Diag=None, F_T1D_Diag=None, F_CVD_Diag=None, F_LD_Diag=None, F_KD_Diag='1996-12-11T00:00:00.000-05:00', HBA1Cct=None, Ct_AlzDiagCode=None, F_AlzDiagDay=None, S_AlzDiagDay=None, L_AlzDiagDay=None, Ct_AlzDementiaDiagCode='1', F_AlzDementia_DiagDay='2017-04-14T00:00:00.000-04:00', S_AlzDementia_DiagDay=None, L_AlzDementia_DiagDay='2017-04-14T00:00:00.000-04:00', F_Neuro_Diag='2017-04-14T00:00:00.000-04:00', F_NeuroDiag_Age='66.57')

In [62]:
df.show()

+---------+---------+------+---------+----------------+--------------------+------+--------------------+-----------+--------------------+--------------------+--------------------+--------------------+-------+--------------+--------------------+------------+--------------------+----------------------+---------------------+---------------------+---------------------+--------------------+---------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|          BIRTH_DATE|diagRL|          F_T2D_Diag|F_GEST_Diag|          F_T1D_Diag|          F_CVD_Diag|           F_LD_Diag|           F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|        F_AlzDiagDay|S_AlzDiagDay|        L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|        F_Neuro_Diag|F_NeuroDiag_Age|
+---------+---------+------+---------+----------------+--------------------+------+--------------------+-----------+--------------------+--------------------+--------------------+--------------------+-------+--------------+--------------------+------------+--------------------+----------------------+---------------------+---------------------+---------------------+--------------------+---------------+
|     1238|       53|     F|    other|african_american|1950-10-06T00:00:...| 22.41|2001-04-07T00:00:...|       null|                null|                null|                null|1996-12-11T00:00:...|   null|          null|                null|        null|                null|                     1| 2017-04-14T00:00:...|                 null| 2017-04-14T00:00:...|2017-04-14T00:00:...|          66.57|
|     1342|       89|     F|    other|african_american|1920-04-19T00:00:...| 20.55|1997-11-03T00:00:...|       null|2001-04-03T00:00:...|1996-11-17T00:00:...|                null|                null|   null|             1|2016-10-28T00:00:...|        null|2016-10-28T00:00:...|                     2| 2011-06-25T00:00:...| 2012-05-06T00:00:...| 2016-10-28T00:00:...|2011-06-25T00:00:...|          91.24|
|     1645|       82|     M|    other|african_american|1928-05-07T00:00:...| 11.94|1999-12-21T00:00:...|       null|2010-12-04T00:00:...|2011-11-02T00:00:...|                null|2011-11-12T00:00:...|      7|          null|                null|        null|                null|                     1| 2011-07-13T00:00:...| 2011-07-15T00:00:...| 2011-07-15T00:00:...|2011-07-13T00:00:...|          83.24|
|     2366|       60|     F|    other|african_american|1948-10-29T00:00:...| 13.33|1996-06-19T00:00:...|       null|1999-06-03T00:00:...|2009-06-10T00:00:...|                null|2009-05-03T00:00:...|      2|          null|                null|        null|                null|                     1| 2009-09-12T00:00:...|                 null| 2009-09-12T00:00:...|2009-09-12T00:00:...|          60.91|
|     2659|       82|     M|    other|           white|1926-12-31T00:00:...| 15.55|2003-04-23T00:00:...|       null|                null|2009-06-27T00:00:...|                null|2012-03-16T00:00:...|      1|          null|                null|        null|                null|                     2| 2012-03-16T00:00:...| 2012-03-30T00:00:...| 2012-12-18T00:00:...|2012-03-16T00:00:...|          85.27|
|     3918|       68|     F|    other|african_american|1942-03-31T00:00:...|  null|                null|       null|                null|                null|                null|                null|     13|          null|                null|        null|                null|                     1| 2017-02-05T01:32:...| 2018-01-19T00:00:...| 2018-02-21T20:42:...|2017-02-05T01:32:...|           74.9|
|     4101|       74|     M|    other|african_american|1937-01-14T00:00:...|  16.1|1997-04-10T00:00:...|       null|2012-03-30T00:00:...|                null|                null|                null|      5|          null|                null|        null|                null|                     1| 2011-08-25T00:00:...|                 null| 2011-08-25T00:00:...|2011-08-25T00:00:...|          74.66|
|     5803|       89|     F|    other|           white|1924-03-06T00:00:...|  7.37|2013-06-05T00:00:...|       null|                null|                null|                null|                null|   null|          null|                null|        null|                null|                     1| 2013-02-22T00:00:...| 2013-05-14T00:00:...| 2013-05-14T00:00:...|2013-02-22T00:00:...|          89.03|
|     6654|       76|     F|    other|african_american|1939-04-08T00:00:...| 18.72|2015-07-08T00:00:...|       null|                null|                null|                null|2017-04-10T00:00:...|      4|          null|                null|        null|                null|                     1| 2017-04-10T00:00:...|                 null| 2017-04-10T00:00:...|2017-04-10T00:00:...|          78.06|
|    12046|       48|     F|    other|           white|1957-01-03T00:00:...|  8.77|2005-04-02T00:00:...|       null|2007-08-03T00:00:...|2013-09-27T00:00:...|                null|2005-03-08T00:00:...|     31|          null|                null|        null|                null|                     1| 2012-12-24T00:00:...| 2013-11-09T00:00:...| 2013-11-09T00:00:...|2012-12-24T00:00:...|          56.01|
|    12799|       63|     F|    other|           other|1940-05-22T00:00:...| 21.93|2003-10-25T00:00:...|       null|                null|                null|                null|2009-03-04T00:00:...|     13|             1|2013-01-05T00:00:...|        null|2013-01-05T00:00:...|                     3| 2012-12-17T00:00:...| 2012-12-19T00:00:...| 2014-06-14T00:00:...|2012-12-17T00:00:...|          72.62|
|    13289|       31|     M|    other|           white|1980-10-05T00:00:...| 16.41|2011-12-18T00:00:...|       null|                null|2003-05-05T00:00:...|2011-10-25T00:00:...|2014-01-03T00:00:...|      2|          null|                null|        null|                null|                     1| 2004-09-07T00:00:...|                 null| 2004-09-07T00:00:...|2004-09-07T00:00:...|          23.94|
|    13623|       77|     M|    other|           white|1939-10-11T00:00:...|  null|                null|       null|                null|2010-12-29T00:00:...|                null|2016-06-30T00:01:...|     22|          null|                null|        null|                null|                     1| 2017-10-15T00:00:...| 2017-10-15T00:01:...| 2018-06-01T00:00:...|2017-10-15T00:00:...|          78.07|
|    13840|       42|     F|    other|           white|1967-02-08T00:00:...|  null|2009-04-27T00:00:...|       null|                null|2009-03-13T00:00:...|2014-12-20T00:00:...|2015-04-18T00:00:...|   null|          null|                null|        null|                null|                     1| 2015-02-07T00:00:...|                 null| 2015-02-07T00:00:...|2015-02-07T00:00:...|          48.03|
|    15727|       58|     M|    other|           white|1951-01-07T00:00:...|  null|2004-11-01T00:00:...|       null|2008-03-19T00:00:...|2010-07-09T00:00:...|                null|2013-07-02T00:00:...|      6|          null|                null|        null|                null|                     1| 2010-07-07T00:00:...|                 null| 2010-07-07T00:00:...|2010-07-07T00:00:...|          59.54|
|    20683|       50|     F|    other|           other|1954-08-27T00:00:...| 17.67|2004-11-13T00:00:...|       null|                null|2001-03-06T00:00:...|                null|                null|      3|          null|                null|        null|                null|                     2| 2011-12-05T00:00:...| 2012-01-09T00:00:...| 2012-02-17T00:00:...|2011-12-05T00:00:...|          57.31|
|    20735|       87|     F|    other|           white|1925-05-11T00:00:...|  5.13|2012-08-11T00:00:...|       null|                null|2012-08-11T00:00:...|                null|                null|   null|          null|                null|        null|                null|                     1| 2013-09-24T00:00:...| 2013-10-01T00:00:...| 2015-11-01T00:00:...|2013-09-24T00:00:...|          88.43|
|    24171|       75|     F|    other|           white|1936-03-01T00:00:...| 18.13|2001-03-14T00:00:...|       null|                null|2004-01-20T00:00:...|                null|                null|      2|          null|                null|        null|                null|                     1| 2013-07-20T00:00:...| 2013-09-07T00:00:...| 2013-11-02T00:00:...|2013-07-20T00:00:...|          77.44|
|    24347|       60|     F|    other|           other|1949-05-14T00:00:...| 10.42|2007-04-08T00:00:...|       null|2008-05-03T00:00:...|2007-04-08T00:00:...|                null|2010-06-28T00:00:...|     11|          null|                null|        null|                null|                     1| 2010-09-07T00:00:...| 2010-11-16T00:00:...| 2010-11-16T00:00:...|2010-09-07T00:00:...|          61.36|
|    28577|       69|     F|    other|african_american|1942-08-20T00:00:...|  null|                null|       null|                null|2011-03-23T00:00:...|                null|                null|     26|          null|                null|        null|                null|                     1| 2011-08-01T00:00:...| 2011-10-24T00:00:...| 2013-09-23T00:00:...|2011-08-01T00:00:...|          68.99|
+---------+---------+------+---------+----------------+--------------------+------+--------------------+-----------+--------------------+--------------------+--------------------+--------------------+-------+--------------+--------------------+------------+--------------------+----------------------+---------------------+---------------------+---------------------+--------------------+---------------+
only showing top 20 rows

In [64]:
df.printSchema()

root
 |-- person_id: string (nullable = true)
 |-- INDEX_AGE: string (nullable = true)
 |-- GENDER: string (nullable = true)
 |-- ETHNICITY: string (nullable = true)
 |-- RACE: string (nullable = true)
 |-- BIRTH_DATE: string (nullable = true)
 |-- diagRL: string (nullable = true)
 |-- F_T2D_Diag: string (nullable = true)
 |-- F_GEST_Diag: string (nullable = true)
 |-- F_T1D_Diag: string (nullable = true)
 |-- F_CVD_Diag: string (nullable = true)
 |-- F_LD_Diag: string (nullable = true)
 |-- F_KD_Diag: string (nullable = true)
 |-- HBA1Cct: string (nullable = true)
 |-- Ct_AlzDiagCode: string (nullable = true)
 |-- F_AlzDiagDay: string (nullable = true)
 |-- S_AlzDiagDay: string (nullable = true)
 |-- L_AlzDiagDay: string (nullable = true)
 |-- Ct_AlzDementiaDiagCode: string (nullable = true)
 |-- F_AlzDementia_DiagDay: string (nullable = true)
 |-- S_AlzDementia_DiagDay: string (nullable = true)
 |-- L_AlzDementia_DiagDay: string (nullable = true)
 |-- F_Neuro_Diag: string (nullable = true)
 |-- F_NeuroDiag_Age: string (nullable = true)

In [43]:
df.describe().show(10)

+-------+------------------+------------------+-----+---------+-----+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+
|summary|               _c0|               _c1|  _c2|      _c3|  _c4|                 _c5|              _c6|                 _c7|                 _c8|                 _c9|                _c10|                _c11|                _c12|             _c13|              _c14|                _c15|                _c16|                _c17|                _c18|                _c19|                _c20|                _c21|                _c22|              _c23|
+-------+------------------+------------------+-----+---------+-----+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+
|  count|             50393|             50393|50393|    50393|50393|               50393|            38327|               43559|                 211|               11821|               26747|                3899|               19956|            25034|              5481|                5341|                2897|                5465|               49764|               49483|               27862|               49758|               50393|             50393|
|   mean|403024.04383632325| 67.99549531671694| null|     null| null|                null|8.618878307154397|                null|                null|                null|                null|                null|                null|5.968002237047098|1.1945255474452554|                null|                null|                null|   1.412053131844945|                null|                null|                null|                null| 70.90765379425378|
| stddev|304620.93276822096|15.533435242570633| null|     null| null|                null|5.502842758141741|                null|                null|                null|                null|                null|                null|6.937645652874809|0.4630212894038503|                null|                null|                null|  0.8031609627485038|                null|                null|                null|                null|15.844104992626313|
|    min|           1000049|                 1|    F|ETHNICITY| RACE|1907-12-15T00:00:...|              0.0|1996-03-15T00:00:...|1996-10-19T00:00:...|1996-03-29T00:00:...|1996-03-25T00:00:...|1996-10-02T00:00:...|1996-03-26T00:01:...|                0|                 1|2002-11-26T00:00:...|2007-01-04T00:00:...|2003-12-13T00:00:...|                   1|1996-03-15T09:05:...|1996-03-30T00:00:...|1996-04-16T15:00:...|1996-03-15T09:05:...|             -2.37|
|    max|         person_id|         INDEX_AGE|    U|    white|white|          BIRTH_DATE|           diagRL|          F_T2D_Diag|         F_GEST_Diag|          F_T1D_Diag|          F_CVD_Diag|           F_LD_Diag|           F_KD_Diag|          HBA1Cct|    Ct_AlzDiagCode|        F_AlzDiagDay|        S_AlzDiagDay|        L_AlzDiagDay|Ct_AlzDementiaDia...|F_AlzDementia_Dia...|S_AlzDementia_Dia...|L_AlzDementia_Dia...|        F_Neuro_Diag|   F_NeuroDiag_Age|
+-------+------------------+------------------+-----+---------+-----+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+

In [68]:
df1=spark.read.format('csv').options(header='true', inferSchema='true').load('/Users/mayam/Desktop/I699/inpc.csv')

In [69]:
df1.show()

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|               null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|               null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|
|     1645|       82|     M|    other|african_american|1928-05-07 00:00:00| 11.94|1999-12-21 00:00:00|       null|2010-12-04 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|      7|          null|               null|        null|               null|                     1|  2011-07-13 00:00:00|  2011-07-15 00:00:00|  2011-07-15 00:00:00|2011-07-13 00:00:00|          83.24|
|     2366|       60|     F|    other|african_american|1948-10-29 00:00:00| 13.33|1996-06-19 00:00:00|       null|1999-06-03 00:00:00|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2009-09-12 00:00:00|                 null|  2009-09-12 00:00:00|2009-09-12 00:00:00|          60.91|
|     2659|       82|     M|    other|           white|1926-12-31 00:00:00| 15.55|2003-04-23 00:00:00|       null|               null|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|      1|          null|               null|        null|               null|                     2|  2012-03-16 00:00:00|  2012-03-30 00:00:00|  2012-12-18 00:00:00|2012-03-16 00:00:00|          85.27|
|     3918|       68|     F|    other|african_american|1942-03-31 00:00:00|  null|               null|       null|               null|               null|               null|               null|     13|          null|               null|        null|               null|                     1|  2017-02-05 01:32:00|  2018-01-19 00:00:00|  2018-02-21 20:42:00|2017-02-05 01:32:00|           74.9|
|     4101|       74|     M|    other|african_american|1937-01-14 00:00:00|  16.1|1997-04-10 00:00:00|       null|2012-03-30 00:00:00|               null|               null|               null|      5|          null|               null|        null|               null|                     1|  2011-08-25 00:00:00|                 null|  2011-08-25 00:00:00|2011-08-25 00:00:00|          74.66|
|     5803|       89|     F|    other|           white|1924-03-06 00:00:00|  7.37|2013-06-05 00:00:00|       null|               null|               null|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-02-22 00:00:00|  2013-05-14 00:00:00|  2013-05-14 00:00:00|2013-02-22 00:00:00|          89.03|
|     6654|       76|     F|    other|african_american|1939-04-08 00:00:00| 18.72|2015-07-08 00:00:00|       null|               null|               null|               null|2017-04-10 00:00:00|      4|          null|               null|        null|               null|                     1|  2017-04-10 00:00:00|                 null|  2017-04-10 00:00:00|2017-04-10 00:00:00|          78.06|
|    12046|       48|     F|    other|           white|1957-01-03 00:00:00|  8.77|2005-04-02 00:00:00|       null|2007-08-03 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|     31|          null|               null|        null|               null|                     1|  2012-12-24 00:00:00|  2013-11-09 00:00:00|  2013-11-09 00:00:00|2012-12-24 00:00:00|          56.01|
|    12799|       63|     F|    other|           other|1940-05-22 00:00:00| 21.93|2003-10-25 00:00:00|       null|               null|               null|               null|2009-03-04 00:00:00|     13|             1|2013-01-05 00:00:00|        null|2013-01-05 00:00:00|                     3|  2012-12-17 00:00:00|  2012-12-19 00:00:00|  2014-06-14 00:00:00|2012-12-17 00:00:00|          72.62|
|    13289|       31|     M|    other|           white|1980-10-05 00:00:00| 16.41|2011-12-18 00:00:00|       null|               null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2004-09-07 00:00:00|                 null|  2004-09-07 00:00:00|2004-09-07 00:00:00|          23.94|
|    13623|       77|     M|    other|           white|1939-10-11 00:00:00|  null|               null|       null|               null|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|     22|          null|               null|        null|               null|                     1|  2017-10-15 00:00:00|  2017-10-15 00:01:00|  2018-06-01 00:00:00|2017-10-15 00:00:00|          78.07|
|    13840|       42|     F|    other|           white|1967-02-08 00:00:00|  null|2009-04-27 00:00:00|       null|               null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|   null|          null|               null|        null|               null|                     1|  2015-02-07 00:00:00|                 null|  2015-02-07 00:00:00|2015-02-07 00:00:00|          48.03|
|    15727|       58|     M|    other|           white|1951-01-07 00:00:00|  null|2004-11-01 00:00:00|       null|2008-03-19 00:00:00|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|      6|          null|               null|        null|               null|                     1|  2010-07-07 00:00:00|                 null|  2010-07-07 00:00:00|2010-07-07 00:00:00|          59.54|
|    20683|       50|     F|    other|           other|1954-08-27 00:00:00| 17.67|2004-11-13 00:00:00|       null|               null|2001-03-06 00:00:00|               null|               null|      3|          null|               null|        null|               null|                     2|  2011-12-05 00:00:00|  2012-01-09 00:00:00|  2012-02-17 00:00:00|2011-12-05 00:00:00|          57.31|
|    20735|       87|     F|    other|           white|1925-05-11 00:00:00|  5.13|2012-08-11 00:00:00|       null|               null|2012-08-11 00:00:00|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-09-24 00:00:00|  2013-10-01 00:00:00|  2015-11-01 00:00:00|2013-09-24 00:00:00|          88.43|
|    24171|       75|     F|    other|           white|1936-03-01 00:00:00| 18.13|2001-03-14 00:00:00|       null|               null|2004-01-20 00:00:00|               null|               null|      2|          null|               null|        null|               null|                     1|  2013-07-20 00:00:00|  2013-09-07 00:00:00|  2013-11-02 00:00:00|2013-07-20 00:00:00|          77.44|
|    24347|       60|     F|    other|           other|1949-05-14 00:00:00| 10.42|2007-04-08 00:00:00|       null|2008-05-03 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|     11|          null|               null|        null|               null|                     1|  2010-09-07 00:00:00|  2010-11-16 00:00:00|  2010-11-16 00:00:00|2010-09-07 00:00:00|          61.36|
|    28577|       69|     F|    other|african_american|1942-08-20 00:00:00|  null|               null|       null|               null|2011-03-23 00:00:00|               null|               null|     26|          null|               null|        null|               null|                     1|  2011-08-01 00:00:00|  2011-10-24 00:00:00|  2013-09-23 00:00:00|2011-08-01 00:00:00|          68.99|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
only showing top 20 rows

In [19]:
import pandas as pd
import numpy as np
inpc=pd.read_csv("/Users/mayam/Desktop/I699/inpc.csv")
inpc

,person_id,INDEX_AGE,GENDER,ETHNICITY,RACE,BIRTH_DATE,diagRL,F_T2D_Diag,F_GEST_Diag,F_T1D_Diag,...,Ct_AlzDiagCode,F_AlzDiagDay,S_AlzDiagDay,L_AlzDiagDay,Ct_AlzDementiaDiagCode,F_AlzDementia_DiagDay,S_AlzDementia_DiagDay,L_AlzDementia_DiagDay,F_Neuro_Diag,F_NeuroDiag_Age
0,1238,53,F,other,african_american,1950-10-06T00:00:00.000-06:00,22.41,2001-04-07T00:00:00.000-05:00,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2017-04-14T00:00:00.000-04:00,NaN,2017-04-14T00:00:00.000-04:00,2017-04-14T00:00:00.000-04:00,66.57
1,1342,89,F,other,african_american,1920-04-19T00:00:00.000-06:00,20.55,1997-11-03T00:00:00.000-05:00,NaN,2001-04-03T00:00:00.000-05:00,...,1.0,2016-10-28T00:00:00.000-04:00,NaN,2016-10-28T00:00:00.000-04:00,2.0,2011-06-25T00:00:00.000-04:00,2012-05-06T00:00:00.000-04:00,2016-10-28T00:00:00.000-04:00,2011-06-25T00:00:00.000-04:00,91.24
2,1645,82,M,other,african_american,1928-05-07T00:00:00.000-06:00,11.94,1999-12-21T00:00:00.000-05:00,NaN,2010-12-04T00:00:00.000-05:00,...,NaN,NaN,NaN,NaN,1.0,2011-07-13T00:00:00.000-04:00,2011-07-15T00:00:00.000-04:00,2011-07-15T00:00:00.000-04:00,2011-07-13T00:00:00.000-04:00,83.24
3,2366,60,F,other,african_american,1948-10-29T00:00:00.000-06:00,13.33,1996-06-19T00:00:00.000-05:00,NaN,1999-06-03T00:00:00.000-05:00,...,NaN,NaN,NaN,NaN,1.0,2009-09-12T00:00:00.000-04:00,NaN,2009-09-12T00:00:00.000-04:00,2009-09-12T00:00:00.000-04:00,60.91
4,2659,82,M,other,white,1926-12-31T00:00:00.000-06:00,15.55,2003-04-23T00:00:00.000-05:00,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2012-03-16T00:00:00.000-04:00,2012-03-30T00:00:00.000-04:00,2012-12-18T00:00:00.000-05:00,2012-03-16T00:00:00.000-04:00,85.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50387,1037813,31,F,other,white,1975-03-29T00:00:00.000-05:00,8.31,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2009-01-19T00:00:00.000-05:00,2009-01-27T00:00:00.000-05:00,2009-11-03T00:00:00.000-05:00,2009-01-19T00:00:00.000-05:00,33.84
50388,1042444,65,M,other,white,1938-06-01T00:00:00.000-06:00,7.34,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2008-01-03T00:00:00.000-05:00,2008-02-03T00:00:00.000-05:00,2014-01-08T00:00:00.000-05:00,2008-01-03T00:00:00.000-05:00,69.64
50389,1043561,76,M,other,white,1927-02-06T00:00:00.000-06:00,10.20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2009-04-06T00:00:00.000-04:00,2009-06-08T00:00:00.000-04:00,2010-03-02T00:00:00.000-05:00,2009-04-06T00:00:00.000-04:00,82.22
50390,1049651,76,F,other,white,1932-07-22T00:00:00.000-06:00,16.06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2008-08-27T00:00:00.000-04:00,2008-08-28T00:00:00.000-04:00,2012-03-29T00:00:00.000-04:00,2008-08-27T00:00:00.000-04:00,76.15
50391,1050663,77,F,other,white,1934-02-18T00:00:00.000-06:00,2.92,2012-02-14T23:53:00.000-05:00,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2013-05-24T00:45:00.000-04:00,NaN,2013-05-24T00:45:00.000-04:00,2013-05-24T00:45:00.000-04:00,79.31

In [20]:
inpc.count()

person_id                 50392
INDEX_AGE                 50392
GENDER                    50392
ETHNICITY                 50392
RACE                      50392
BIRTH_DATE                50392
diagRL                    38326
F_T2D_Diag                43558
F_GEST_Diag                 210
F_T1D_Diag                11820
F_CVD_Diag                26746
F_LD_Diag                  3898
F_KD_Diag                 19955
HBA1Cct                   25033
Ct_AlzDiagCode             5480
F_AlzDiagDay               5340
S_AlzDiagDay               2896
L_AlzDiagDay               5464
Ct_AlzDementiaDiagCode    49763
F_AlzDementia_DiagDay     49482
S_AlzDementia_DiagDay     27861
L_AlzDementia_DiagDay     49757
F_Neuro_Diag              50392
F_NeuroDiag_Age           50392
dtype: int64

In [22]:
inpc.columns

Index(['person_id', 'INDEX_AGE', 'GENDER', 'ETHNICITY', 'RACE', 'BIRTH_DATE',
       'diagRL', 'F_T2D_Diag', 'F_GEST_Diag', 'F_T1D_Diag', 'F_CVD_Diag',
       'F_LD_Diag', 'F_KD_Diag', 'HBA1Cct', 'Ct_AlzDiagCode', 'F_AlzDiagDay',
       'S_AlzDiagDay', 'L_AlzDiagDay', 'Ct_AlzDementiaDiagCode',
       'F_AlzDementia_DiagDay', 'S_AlzDementia_DiagDay',
       'L_AlzDementia_DiagDay', 'F_Neuro_Diag', 'F_NeuroDiag_Age'],
      dtype='object')

In [55]:
inpc[['INDEX_AGE','GENDER']]

       INDEX_AGE GENDER
0             53      F
1             89      F
2             82      M
3             60      F
4             82      M
...          ...    ...
50387         31      F
50388         65      M
50389         76      M
50390         76      F
50391         77      F

[50392 rows x 2 columns]

In [60]:
inpc.loc['']

KeyError: 'F'