In [1]:
# Reading the csv file into the dataframe

df = spark.read.csv("/Users/mayam/Desktop/I699/inpc.csv", header='true', inferSchema='true')
df.show()

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|               null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|               null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|
|     1645|       82|     M|    other|african_american|1928-05-07 00:00:00| 11.94|1999-12-21 00:00:00|       null|2010-12-04 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|      7|          null|               null|        null|               null|                     1|  2011-07-13 00:00:00|  2011-07-15 00:00:00|  2011-07-15 00:00:00|2011-07-13 00:00:00|          83.24|
|     2366|       60|     F|    other|african_american|1948-10-29 00:00:00| 13.33|1996-06-19 00:00:00|       null|1999-06-03 00:00:00|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2009-09-12 00:00:00|                 null|  2009-09-12 00:00:00|2009-09-12 00:00:00|          60.91|
|     2659|       82|     M|    other|           white|1926-12-31 00:00:00| 15.55|2003-04-23 00:00:00|       null|               null|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|      1|          null|               null|        null|               null|                     2|  2012-03-16 00:00:00|  2012-03-30 00:00:00|  2012-12-18 00:00:00|2012-03-16 00:00:00|          85.27|
|     3918|       68|     F|    other|african_american|1942-03-31 00:00:00|  null|               null|       null|               null|               null|               null|               null|     13|          null|               null|        null|               null|                     1|  2017-02-05 01:32:00|  2018-01-19 00:00:00|  2018-02-21 20:42:00|2017-02-05 01:32:00|           74.9|
|     4101|       74|     M|    other|african_american|1937-01-14 00:00:00|  16.1|1997-04-10 00:00:00|       null|2012-03-30 00:00:00|               null|               null|               null|      5|          null|               null|        null|               null|                     1|  2011-08-25 00:00:00|                 null|  2011-08-25 00:00:00|2011-08-25 00:00:00|          74.66|
|     5803|       89|     F|    other|           white|1924-03-06 00:00:00|  7.37|2013-06-05 00:00:00|       null|               null|               null|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-02-22 00:00:00|  2013-05-14 00:00:00|  2013-05-14 00:00:00|2013-02-22 00:00:00|          89.03|
|     6654|       76|     F|    other|african_american|1939-04-08 00:00:00| 18.72|2015-07-08 00:00:00|       null|               null|               null|               null|2017-04-10 00:00:00|      4|          null|               null|        null|               null|                     1|  2017-04-10 00:00:00|                 null|  2017-04-10 00:00:00|2017-04-10 00:00:00|          78.06|
|    12046|       48|     F|    other|           white|1957-01-03 00:00:00|  8.77|2005-04-02 00:00:00|       null|2007-08-03 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|     31|          null|               null|        null|               null|                     1|  2012-12-24 00:00:00|  2013-11-09 00:00:00|  2013-11-09 00:00:00|2012-12-24 00:00:00|          56.01|
|    12799|       63|     F|    other|           other|1940-05-22 00:00:00| 21.93|2003-10-25 00:00:00|       null|               null|               null|               null|2009-03-04 00:00:00|     13|             1|2013-01-05 00:00:00|        null|2013-01-05 00:00:00|                     3|  2012-12-17 00:00:00|  2012-12-19 00:00:00|  2014-06-14 00:00:00|2012-12-17 00:00:00|          72.62|
|    13289|       31|     M|    other|           white|1980-10-05 00:00:00| 16.41|2011-12-18 00:00:00|       null|               null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2004-09-07 00:00:00|                 null|  2004-09-07 00:00:00|2004-09-07 00:00:00|          23.94|
|    13623|       77|     M|    other|           white|1939-10-11 00:00:00|  null|               null|       null|               null|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|     22|          null|               null|        null|               null|                     1|  2017-10-15 00:00:00|  2017-10-15 00:01:00|  2018-06-01 00:00:00|2017-10-15 00:00:00|          78.07|
|    13840|       42|     F|    other|           white|1967-02-08 00:00:00|  null|2009-04-27 00:00:00|       null|               null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|   null|          null|               null|        null|               null|                     1|  2015-02-07 00:00:00|                 null|  2015-02-07 00:00:00|2015-02-07 00:00:00|          48.03|
|    15727|       58|     M|    other|           white|1951-01-07 00:00:00|  null|2004-11-01 00:00:00|       null|2008-03-19 00:00:00|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|      6|          null|               null|        null|               null|                     1|  2010-07-07 00:00:00|                 null|  2010-07-07 00:00:00|2010-07-07 00:00:00|          59.54|
|    20683|       50|     F|    other|           other|1954-08-27 00:00:00| 17.67|2004-11-13 00:00:00|       null|               null|2001-03-06 00:00:00|               null|               null|      3|          null|               null|        null|               null|                     2|  2011-12-05 00:00:00|  2012-01-09 00:00:00|  2012-02-17 00:00:00|2011-12-05 00:00:00|          57.31|
|    20735|       87|     F|    other|           white|1925-05-11 00:00:00|  5.13|2012-08-11 00:00:00|       null|               null|2012-08-11 00:00:00|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-09-24 00:00:00|  2013-10-01 00:00:00|  2015-11-01 00:00:00|2013-09-24 00:00:00|          88.43|
|    24171|       75|     F|    other|           white|1936-03-01 00:00:00| 18.13|2001-03-14 00:00:00|       null|               null|2004-01-20 00:00:00|               null|               null|      2|          null|               null|        null|               null|                     1|  2013-07-20 00:00:00|  2013-09-07 00:00:00|  2013-11-02 00:00:00|2013-07-20 00:00:00|          77.44|
|    24347|       60|     F|    other|           other|1949-05-14 00:00:00| 10.42|2007-04-08 00:00:00|       null|2008-05-03 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|     11|          null|               null|        null|               null|                     1|  2010-09-07 00:00:00|  2010-11-16 00:00:00|  2010-11-16 00:00:00|2010-09-07 00:00:00|          61.36|
|    28577|       69|     F|    other|african_american|1942-08-20 00:00:00|  null|               null|       null|               null|2011-03-23 00:00:00|               null|               null|     26|          null|               null|        null|               null|                     1|  2011-08-01 00:00:00|  2011-10-24 00:00:00|  2013-09-23 00:00:00|2011-08-01 00:00:00|          68.99|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
only showing top 20 rows

EXPLORING DATASET:

In [2]:
# Printing the schema of the dataset
df.printSchema()

root
 |-- person_id: integer (nullable = true)
 |-- INDEX_AGE: integer (nullable = true)
 |-- GENDER: string (nullable = true)
 |-- ETHNICITY: string (nullable = true)
 |-- RACE: string (nullable = true)
 |-- BIRTH_DATE: timestamp (nullable = true)
 |-- diagRL: double (nullable = true)
 |-- F_T2D_Diag: timestamp (nullable = true)
 |-- F_GEST_Diag: timestamp (nullable = true)
 |-- F_T1D_Diag: timestamp (nullable = true)
 |-- F_CVD_Diag: timestamp (nullable = true)
 |-- F_LD_Diag: timestamp (nullable = true)
 |-- F_KD_Diag: timestamp (nullable = true)
 |-- HBA1Cct: integer (nullable = true)
 |-- Ct_AlzDiagCode: integer (nullable = true)
 |-- F_AlzDiagDay: timestamp (nullable = true)
 |-- S_AlzDiagDay: timestamp (nullable = true)
 |-- L_AlzDiagDay: timestamp (nullable = true)
 |-- Ct_AlzDementiaDiagCode: integer (nullable = true)
 |-- F_AlzDementia_DiagDay: timestamp (nullable = true)
 |-- S_AlzDementia_DiagDay: timestamp (nullable = true)
 |-- L_AlzDementia_DiagDay: timestamp (nullable = true)
 |-- F_Neuro_Diag: timestamp (nullable = true)
 |-- F_NeuroDiag_Age: double (nullable = true)

In [3]:
df.show(2,truncate= True)

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+---------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+---------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|     null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|     null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+---------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+
only showing top 2 rows

In [4]:
#total count
df.count()

50392

In [5]:
#count row and column
def shape(self):
    return (self.count(), len(self.columns))
shape(df)

(50392, 24)

In [6]:
#length of column
len(df.columns), df.columns

(24,
 ['person_id',
  'INDEX_AGE',
  'GENDER',
  'ETHNICITY',
  'RACE',
  'BIRTH_DATE',
  'diagRL',
  'F_T2D_Diag',
  'F_GEST_Diag',
  'F_T1D_Diag',
  'F_CVD_Diag',
  'F_LD_Diag',
  'F_KD_Diag',
  'HBA1Cct',
  'Ct_AlzDiagCode',
  'F_AlzDiagDay',
  'S_AlzDiagDay',
  'L_AlzDiagDay',
  'Ct_AlzDementiaDiagCode',
  'F_AlzDementia_DiagDay',
  'S_AlzDementia_DiagDay',
  'L_AlzDementia_DiagDay',
  'F_Neuro_Diag',
  'F_NeuroDiag_Age'])

In [7]:
df.describe().show()

+-------+------------------+------------------+------+---------+-------+-----------------+-----------------+------------------+----------------------+-----------------+
|summary|         person_id|         INDEX_AGE|GENDER|ETHNICITY|   RACE|           diagRL|          HBA1Cct|    Ct_AlzDiagCode|Ct_AlzDementiaDiagCode|  F_NeuroDiag_Age|
+-------+------------------+------------------+------+---------+-------+-----------------+-----------------+------------------+----------------------+-----------------+
|  count|             50392|             50392| 50392|    50392|  50392|            38326|            25033|              5480|                 49763|            50392|
|   mean|403024.04383632325| 67.99549531671694|  null|     null|   null|8.618878307154407|5.968002237047098|1.1945255474452554|     1.412053131844945|70.90765379425373|
| stddev|304620.93276822165|15.533435242570624|  null|     null|   null|5.502842758141747|6.937645652874809|0.4630212894038504|     0.803160962748505|15.84410499262631|
|    min|                 3|                 1|     F| hispanic|_ERROR_|              0.0|                0|                 1|                     1|            -2.37|
|    max|           1060934|                89|     U|    white|  white|            23.12|               85|                 4|                    10|           101.59|
+-------+------------------+------------------+------+---------+-------+-----------------+-----------------+------------------+----------------------+-----------------+

In [7]:
df.select("INDEX_AGE","BIRTH_DATE","GENDER","F_T2D_Diag","F_AlzDiagDay","S_AlzDiagDay",\
               "F_AlzDementia_DiagDay","S_AlzDementia_DiagDay",'F_CVD_Diag','F_LD_Diag', 'F_KD_Diag').show()

+---------+-------------------+------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
|INDEX_AGE|         BIRTH_DATE|GENDER|         F_T2D_Diag|       F_AlzDiagDay|S_AlzDiagDay|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|
+---------+-------------------+------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
|       53|1950-10-06 00:00:00|     F|2001-04-07 00:00:00|               null|        null|  2017-04-14 00:00:00|                 null|               null|               null|1996-12-11 00:00:00|
|       89|1920-04-19 00:00:00|     F|1997-11-03 00:00:00|2016-10-28 00:00:00|        null|  2011-06-25 00:00:00|  2012-05-06 00:00:00|1996-11-17 00:00:00|               null|               null|
|       82|1928-05-07 00:00:00|     M|1999-12-21 00:00:00|               null|        null|  2011-07-13 00:00:00|  2011-07-15 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|
|       60|1948-10-29 00:00:00|     F|1996-06-19 00:00:00|               null|        null|  2009-09-12 00:00:00|                 null|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|
|       82|1926-12-31 00:00:00|     M|2003-04-23 00:00:00|               null|        null|  2012-03-16 00:00:00|  2012-03-30 00:00:00|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|
|       68|1942-03-31 00:00:00|     F|               null|               null|        null|  2017-02-05 01:32:00|  2018-01-19 00:00:00|               null|               null|               null|
|       74|1937-01-14 00:00:00|     M|1997-04-10 00:00:00|               null|        null|  2011-08-25 00:00:00|                 null|               null|               null|               null|
|       89|1924-03-06 00:00:00|     F|2013-06-05 00:00:00|               null|        null|  2013-02-22 00:00:00|  2013-05-14 00:00:00|               null|               null|               null|
|       76|1939-04-08 00:00:00|     F|2015-07-08 00:00:00|               null|        null|  2017-04-10 00:00:00|                 null|               null|               null|2017-04-10 00:00:00|
|       48|1957-01-03 00:00:00|     F|2005-04-02 00:00:00|               null|        null|  2012-12-24 00:00:00|  2013-11-09 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|
|       63|1940-05-22 00:00:00|     F|2003-10-25 00:00:00|2013-01-05 00:00:00|        null|  2012-12-17 00:00:00|  2012-12-19 00:00:00|               null|               null|2009-03-04 00:00:00|
|       31|1980-10-05 00:00:00|     M|2011-12-18 00:00:00|               null|        null|  2004-09-07 00:00:00|                 null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|
|       77|1939-10-11 00:00:00|     M|               null|               null|        null|  2017-10-15 00:00:00|  2017-10-15 00:01:00|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|
|       42|1967-02-08 00:00:00|     F|2009-04-27 00:00:00|               null|        null|  2015-02-07 00:00:00|                 null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|
|       58|1951-01-07 00:00:00|     M|2004-11-01 00:00:00|               null|        null|  2010-07-07 00:00:00|                 null|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|
|       50|1954-08-27 00:00:00|     F|2004-11-13 00:00:00|               null|        null|  2011-12-05 00:00:00|  2012-01-09 00:00:00|2001-03-06 00:00:00|               null|               null|
|       87|1925-05-11 00:00:00|     F|2012-08-11 00:00:00|               null|        null|  2013-09-24 00:00:00|  2013-10-01 00:00:00|2012-08-11 00:00:00|               null|               null|
|       75|1936-03-01 00:00:00|     F|2001-03-14 00:00:00|               null|        null|  2013-07-20 00:00:00|  2013-09-07 00:00:00|2004-01-20 00:00:00|               null|               null|
|       60|1949-05-14 00:00:00|     F|2007-04-08 00:00:00|               null|        null|  2010-09-07 00:00:00|  2010-11-16 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|
|       69|1942-08-20 00:00:00|     F|               null|               null|        null|  2011-08-01 00:00:00|  2011-10-24 00:00:00|2011-03-23 00:00:00|               null|               null|
+---------+-------------------+------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
only showing top 20 rows

In [8]:
df.select("BIRTH_DATE","F_T2D_Diag","F_AlzDiagDay","S_AlzDiagDay",
               "F_AlzDementia_DiagDay","S_AlzDementia_DiagDay",'F_CVD_Diag','F_LD_Diag', 'F_KD_Diag').show()

+-------------------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
|         BIRTH_DATE|         F_T2D_Diag|       F_AlzDiagDay|S_AlzDiagDay|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|
+-------------------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
|1950-10-06 00:00:00|2001-04-07 00:00:00|               null|        null|  2017-04-14 00:00:00|                 null|               null|               null|1996-12-11 00:00:00|
|1920-04-19 00:00:00|1997-11-03 00:00:00|2016-10-28 00:00:00|        null|  2011-06-25 00:00:00|  2012-05-06 00:00:00|1996-11-17 00:00:00|               null|               null|
|1928-05-07 00:00:00|1999-12-21 00:00:00|               null|        null|  2011-07-13 00:00:00|  2011-07-15 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|
|1948-10-29 00:00:00|1996-06-19 00:00:00|               null|        null|  2009-09-12 00:00:00|                 null|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|
|1926-12-31 00:00:00|2003-04-23 00:00:00|               null|        null|  2012-03-16 00:00:00|  2012-03-30 00:00:00|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|
|1942-03-31 00:00:00|               null|               null|        null|  2017-02-05 01:32:00|  2018-01-19 00:00:00|               null|               null|               null|
|1937-01-14 00:00:00|1997-04-10 00:00:00|               null|        null|  2011-08-25 00:00:00|                 null|               null|               null|               null|
|1924-03-06 00:00:00|2013-06-05 00:00:00|               null|        null|  2013-02-22 00:00:00|  2013-05-14 00:00:00|               null|               null|               null|
|1939-04-08 00:00:00|2015-07-08 00:00:00|               null|        null|  2017-04-10 00:00:00|                 null|               null|               null|2017-04-10 00:00:00|
|1957-01-03 00:00:00|2005-04-02 00:00:00|               null|        null|  2012-12-24 00:00:00|  2013-11-09 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|
|1940-05-22 00:00:00|2003-10-25 00:00:00|2013-01-05 00:00:00|        null|  2012-12-17 00:00:00|  2012-12-19 00:00:00|               null|               null|2009-03-04 00:00:00|
|1980-10-05 00:00:00|2011-12-18 00:00:00|               null|        null|  2004-09-07 00:00:00|                 null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|
|1939-10-11 00:00:00|               null|               null|        null|  2017-10-15 00:00:00|  2017-10-15 00:01:00|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|
|1967-02-08 00:00:00|2009-04-27 00:00:00|               null|        null|  2015-02-07 00:00:00|                 null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|
|1951-01-07 00:00:00|2004-11-01 00:00:00|               null|        null|  2010-07-07 00:00:00|                 null|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|
|1954-08-27 00:00:00|2004-11-13 00:00:00|               null|        null|  2011-12-05 00:00:00|  2012-01-09 00:00:00|2001-03-06 00:00:00|               null|               null|
|1925-05-11 00:00:00|2012-08-11 00:00:00|               null|        null|  2013-09-24 00:00:00|  2013-10-01 00:00:00|2012-08-11 00:00:00|               null|               null|
|1936-03-01 00:00:00|2001-03-14 00:00:00|               null|        null|  2013-07-20 00:00:00|  2013-09-07 00:00:00|2004-01-20 00:00:00|               null|               null|
|1949-05-14 00:00:00|2007-04-08 00:00:00|               null|        null|  2010-09-07 00:00:00|  2010-11-16 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|
|1942-08-20 00:00:00|               null|               null|        null|  2011-08-01 00:00:00|  2011-10-24 00:00:00|2011-03-23 00:00:00|               null|               null|
+-------------------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
only showing top 20 rows

In [9]:
from pyspark.sql.functions import rank, col, unix_timestamp, from_unixtime, to_timestamp
from pyspark.sql import functions as F
timeFmt = "yyyy-MM-dd"
#time_T2DAge = (F.unix_timestamp('BIRTH_DATE', format=timeFmt) - F.unix_timestamp('DOB', format=timeFmt))
df.select('BIRTH_DATE',from_unixtime(unix_timestamp('BIRTH_DATE', 'MM/dd/yyy')).alias('DOB'))
df.select('F_T2D_Diag',from_unixtime(unix_timestamp('F_T2D_Diag', 'MM/dd/yyy')).alias('FT2D'))
df.select('F_AlzDiagDay',from_unixtime(unix_timestamp('F_AlzDiagDay', 'MM/dd/yyy')).alias('F_AD_DAY'))
df.select('S_AlzDiagDay',from_unixtime(unix_timestamp('S_AlzDiagDay', 'MM/dd/yyy')).alias('S_AD_DAY'))
df.select('F_AlzDementia_DiagDay',from_unixtime(unix_timestamp('F_AlzDementia_DiagDay', 'MM/dd/yyy')).alias('FAD_DEM_DAY'))
df.select('S_AlzDementia_DiagDay',from_unixtime(unix_timestamp('S_AlzDementia_DiagDay', 'MM/dd/yyy')).alias('SAD_DEM_DAY'))

DataFrame[S_AlzDementia_DiagDay: timestamp, SAD_DEM_DAY: string]

In [10]:
df.select("BIRTH_DATE","F_T2D_Diag","F_AlzDiagDay","S_AlzDiagDay",
               "F_AlzDementia_DiagDay","S_AlzDementia_DiagDay",'F_CVD_Diag','F_LD_Diag', 'F_KD_Diag').describe()

DataFrame[summary: string]

In [11]:
df.select("BIRTH_DATE","F_T2D_Diag","F_AlzDiagDay","S_AlzDiagDay",
               "F_AlzDementia_DiagDay","S_AlzDementia_DiagDay",'F_CVD_Diag','F_LD_Diag', 'F_KD_Diag').show()

+-------------------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
|         BIRTH_DATE|         F_T2D_Diag|       F_AlzDiagDay|S_AlzDiagDay|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|
+-------------------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
|1950-10-06 00:00:00|2001-04-07 00:00:00|               null|        null|  2017-04-14 00:00:00|                 null|               null|               null|1996-12-11 00:00:00|
|1920-04-19 00:00:00|1997-11-03 00:00:00|2016-10-28 00:00:00|        null|  2011-06-25 00:00:00|  2012-05-06 00:00:00|1996-11-17 00:00:00|               null|               null|
|1928-05-07 00:00:00|1999-12-21 00:00:00|               null|        null|  2011-07-13 00:00:00|  2011-07-15 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|
|1948-10-29 00:00:00|1996-06-19 00:00:00|               null|        null|  2009-09-12 00:00:00|                 null|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|
|1926-12-31 00:00:00|2003-04-23 00:00:00|               null|        null|  2012-03-16 00:00:00|  2012-03-30 00:00:00|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|
|1942-03-31 00:00:00|               null|               null|        null|  2017-02-05 01:32:00|  2018-01-19 00:00:00|               null|               null|               null|
|1937-01-14 00:00:00|1997-04-10 00:00:00|               null|        null|  2011-08-25 00:00:00|                 null|               null|               null|               null|
|1924-03-06 00:00:00|2013-06-05 00:00:00|               null|        null|  2013-02-22 00:00:00|  2013-05-14 00:00:00|               null|               null|               null|
|1939-04-08 00:00:00|2015-07-08 00:00:00|               null|        null|  2017-04-10 00:00:00|                 null|               null|               null|2017-04-10 00:00:00|
|1957-01-03 00:00:00|2005-04-02 00:00:00|               null|        null|  2012-12-24 00:00:00|  2013-11-09 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|
|1940-05-22 00:00:00|2003-10-25 00:00:00|2013-01-05 00:00:00|        null|  2012-12-17 00:00:00|  2012-12-19 00:00:00|               null|               null|2009-03-04 00:00:00|
|1980-10-05 00:00:00|2011-12-18 00:00:00|               null|        null|  2004-09-07 00:00:00|                 null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|
|1939-10-11 00:00:00|               null|               null|        null|  2017-10-15 00:00:00|  2017-10-15 00:01:00|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|
|1967-02-08 00:00:00|2009-04-27 00:00:00|               null|        null|  2015-02-07 00:00:00|                 null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|
|1951-01-07 00:00:00|2004-11-01 00:00:00|               null|        null|  2010-07-07 00:00:00|                 null|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|
|1954-08-27 00:00:00|2004-11-13 00:00:00|               null|        null|  2011-12-05 00:00:00|  2012-01-09 00:00:00|2001-03-06 00:00:00|               null|               null|
|1925-05-11 00:00:00|2012-08-11 00:00:00|               null|        null|  2013-09-24 00:00:00|  2013-10-01 00:00:00|2012-08-11 00:00:00|               null|               null|
|1936-03-01 00:00:00|2001-03-14 00:00:00|               null|        null|  2013-07-20 00:00:00|  2013-09-07 00:00:00|2004-01-20 00:00:00|               null|               null|
|1949-05-14 00:00:00|2007-04-08 00:00:00|               null|        null|  2010-09-07 00:00:00|  2010-11-16 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|
|1942-08-20 00:00:00|               null|               null|        null|  2011-08-01 00:00:00|  2011-10-24 00:00:00|2011-03-23 00:00:00|               null|               null|
+-------------------+-------------------+-------------------+------------+---------------------+---------------------+-------------------+-------------------+-------------------+
only showing top 20 rows

In [12]:
YearDiff = (unix_timestamp('S_AlzDiagDay', "yyyy-MM-dd HH:mm:ss") - unix_timestamp('F_AlzDiagDay', "yyyy-MM-dd HH:mm:ss"))
df = df.withColumn("Year_AD_Diag", YearDiff)
df.show()

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|Year_AD_Diag|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|               null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|        null|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|               null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|        null|
|     1645|       82|     M|    other|african_american|1928-05-07 00:00:00| 11.94|1999-12-21 00:00:00|       null|2010-12-04 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|      7|          null|               null|        null|               null|                     1|  2011-07-13 00:00:00|  2011-07-15 00:00:00|  2011-07-15 00:00:00|2011-07-13 00:00:00|          83.24|        null|
|     2366|       60|     F|    other|african_american|1948-10-29 00:00:00| 13.33|1996-06-19 00:00:00|       null|1999-06-03 00:00:00|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2009-09-12 00:00:00|                 null|  2009-09-12 00:00:00|2009-09-12 00:00:00|          60.91|        null|
|     2659|       82|     M|    other|           white|1926-12-31 00:00:00| 15.55|2003-04-23 00:00:00|       null|               null|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|      1|          null|               null|        null|               null|                     2|  2012-03-16 00:00:00|  2012-03-30 00:00:00|  2012-12-18 00:00:00|2012-03-16 00:00:00|          85.27|        null|
|     3918|       68|     F|    other|african_american|1942-03-31 00:00:00|  null|               null|       null|               null|               null|               null|               null|     13|          null|               null|        null|               null|                     1|  2017-02-05 01:32:00|  2018-01-19 00:00:00|  2018-02-21 20:42:00|2017-02-05 01:32:00|           74.9|        null|
|     4101|       74|     M|    other|african_american|1937-01-14 00:00:00|  16.1|1997-04-10 00:00:00|       null|2012-03-30 00:00:00|               null|               null|               null|      5|          null|               null|        null|               null|                     1|  2011-08-25 00:00:00|                 null|  2011-08-25 00:00:00|2011-08-25 00:00:00|          74.66|        null|
|     5803|       89|     F|    other|           white|1924-03-06 00:00:00|  7.37|2013-06-05 00:00:00|       null|               null|               null|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-02-22 00:00:00|  2013-05-14 00:00:00|  2013-05-14 00:00:00|2013-02-22 00:00:00|          89.03|        null|
|     6654|       76|     F|    other|african_american|1939-04-08 00:00:00| 18.72|2015-07-08 00:00:00|       null|               null|               null|               null|2017-04-10 00:00:00|      4|          null|               null|        null|               null|                     1|  2017-04-10 00:00:00|                 null|  2017-04-10 00:00:00|2017-04-10 00:00:00|          78.06|        null|
|    12046|       48|     F|    other|           white|1957-01-03 00:00:00|  8.77|2005-04-02 00:00:00|       null|2007-08-03 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|     31|          null|               null|        null|               null|                     1|  2012-12-24 00:00:00|  2013-11-09 00:00:00|  2013-11-09 00:00:00|2012-12-24 00:00:00|          56.01|        null|
|    12799|       63|     F|    other|           other|1940-05-22 00:00:00| 21.93|2003-10-25 00:00:00|       null|               null|               null|               null|2009-03-04 00:00:00|     13|             1|2013-01-05 00:00:00|        null|2013-01-05 00:00:00|                     3|  2012-12-17 00:00:00|  2012-12-19 00:00:00|  2014-06-14 00:00:00|2012-12-17 00:00:00|          72.62|        null|
|    13289|       31|     M|    other|           white|1980-10-05 00:00:00| 16.41|2011-12-18 00:00:00|       null|               null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2004-09-07 00:00:00|                 null|  2004-09-07 00:00:00|2004-09-07 00:00:00|          23.94|        null|
|    13623|       77|     M|    other|           white|1939-10-11 00:00:00|  null|               null|       null|               null|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|     22|          null|               null|        null|               null|                     1|  2017-10-15 00:00:00|  2017-10-15 00:01:00|  2018-06-01 00:00:00|2017-10-15 00:00:00|          78.07|        null|
|    13840|       42|     F|    other|           white|1967-02-08 00:00:00|  null|2009-04-27 00:00:00|       null|               null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|   null|          null|               null|        null|               null|                     1|  2015-02-07 00:00:00|                 null|  2015-02-07 00:00:00|2015-02-07 00:00:00|          48.03|        null|
|    15727|       58|     M|    other|           white|1951-01-07 00:00:00|  null|2004-11-01 00:00:00|       null|2008-03-19 00:00:00|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|      6|          null|               null|        null|               null|                     1|  2010-07-07 00:00:00|                 null|  2010-07-07 00:00:00|2010-07-07 00:00:00|          59.54|        null|
|    20683|       50|     F|    other|           other|1954-08-27 00:00:00| 17.67|2004-11-13 00:00:00|       null|               null|2001-03-06 00:00:00|               null|               null|      3|          null|               null|        null|               null|                     2|  2011-12-05 00:00:00|  2012-01-09 00:00:00|  2012-02-17 00:00:00|2011-12-05 00:00:00|          57.31|        null|
|    20735|       87|     F|    other|           white|1925-05-11 00:00:00|  5.13|2012-08-11 00:00:00|       null|               null|2012-08-11 00:00:00|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-09-24 00:00:00|  2013-10-01 00:00:00|  2015-11-01 00:00:00|2013-09-24 00:00:00|          88.43|        null|
|    24171|       75|     F|    other|           white|1936-03-01 00:00:00| 18.13|2001-03-14 00:00:00|       null|               null|2004-01-20 00:00:00|               null|               null|      2|          null|               null|        null|               null|                     1|  2013-07-20 00:00:00|  2013-09-07 00:00:00|  2013-11-02 00:00:00|2013-07-20 00:00:00|          77.44|        null|
|    24347|       60|     F|    other|           other|1949-05-14 00:00:00| 10.42|2007-04-08 00:00:00|       null|2008-05-03 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|     11|          null|               null|        null|               null|                     1|  2010-09-07 00:00:00|  2010-11-16 00:00:00|  2010-11-16 00:00:00|2010-09-07 00:00:00|          61.36|        null|
|    28577|       69|     F|    other|african_american|1942-08-20 00:00:00|  null|               null|       null|               null|2011-03-23 00:00:00|               null|               null|     26|          null|               null|        null|               null|                     1|  2011-08-01 00:00:00|  2011-10-24 00:00:00|  2013-09-23 00:00:00|2011-08-01 00:00:00|          68.99|        null|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+
only showing top 20 rows

In [13]:
df.select("BIRTH_DATE").show()

+-------------------+
|         BIRTH_DATE|
+-------------------+
|1950-10-06 00:00:00|
|1920-04-19 00:00:00|
|1928-05-07 00:00:00|
|1948-10-29 00:00:00|
|1926-12-31 00:00:00|
|1942-03-31 00:00:00|
|1937-01-14 00:00:00|
|1924-03-06 00:00:00|
|1939-04-08 00:00:00|
|1957-01-03 00:00:00|
|1940-05-22 00:00:00|
|1980-10-05 00:00:00|
|1939-10-11 00:00:00|
|1967-02-08 00:00:00|
|1951-01-07 00:00:00|
|1954-08-27 00:00:00|
|1925-05-11 00:00:00|
|1936-03-01 00:00:00|
|1949-05-14 00:00:00|
|1942-08-20 00:00:00|
+-------------------+
only showing top 20 rows

In [30]:
df.filter("Year_AD_Diag is not NULL").count()

2772

In [31]:
df.filter("BIRTH_DATE is NULL").count()

0

In [32]:
df.select("Year_AD_Diag").show()

+------------+
|Year_AD_Diag|
+------------+
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
|        null|
+------------+
only showing top 20 rows

In [24]:
df.filter("Year_AD_Diag is not NULL").count()

2772

In [25]:
df.filter("Year_AD_Diag is NULL").count()

47620

In [37]:
YearDiff = (unix_timestamp('S_AlzDementia_DiagDay', "yyyy-MM-dd HH:mm:ss") - unix_timestamp('F_AlzDementia_DiagDay', "yyyy-MM-dd HH:mm:ss"))
df = df.withColumn("Year_AD_Dem_Diag", YearDiff)
df.show(2)

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+---------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|Year_AD_Diag|Year_AD_Dem_Diag|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+---------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|     null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|        null|            null|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|     null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|        null|        27302400|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+---------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+
only showing top 2 rows

In [27]:
df.filter("Year_AD_Dem_Diag is not NULL").count()

27586

In [28]:
df.filter("Year_AD_Dem_Diag is NULL").count()

22806

In [50]:
YearDiff = (unix_timestamp('F_AlzDiagDay', "yyyy-MM-dd HH:mm:ss") - unix_timestamp('BIRTH_DATE', "yyyy-MM-dd HH:mm:ss"))
df = df.withColumn("Age_AD_Diag", YearDiff/365)
df.show()

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+---------------+-----------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|Year_AD_Diag|Year_AD_Dem_Diag|Age_AD_Dem_Diag|      Age_AD_Diag|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+---------------+-----------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|               null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|        null|            null|     2099253600|             null|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|               null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|        null|        27302400|     2877458400|8345510.136986301|
|     1645|       82|     M|    other|african_american|1928-05-07 00:00:00| 11.94|1999-12-21 00:00:00|       null|2010-12-04 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|      7|          null|               null|        null|               null|                     1|  2011-07-13 00:00:00|  2011-07-15 00:00:00|  2011-07-15 00:00:00|2011-07-13 00:00:00|          83.24|        null|          172800|     2624997600|             null|
|     2366|       60|     F|    other|african_american|1948-10-29 00:00:00| 13.33|1996-06-19 00:00:00|       null|1999-06-03 00:00:00|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2009-09-12 00:00:00|                 null|  2009-09-12 00:00:00|2009-09-12 00:00:00|          60.91|        null|            null|     1920924000|             null|
|     2659|       82|     M|    other|           white|1926-12-31 00:00:00| 15.55|2003-04-23 00:00:00|       null|               null|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|      1|          null|               null|        null|               null|                     2|  2012-03-16 00:00:00|  2012-03-30 00:00:00|  2012-12-18 00:00:00|2012-03-16 00:00:00|          85.27|        null|         1209600|     2688933600|             null|
|     3918|       68|     F|    other|african_american|1942-03-31 00:00:00|  null|               null|       null|               null|               null|               null|               null|     13|          null|               null|        null|               null|                     1|  2017-02-05 01:32:00|  2018-01-19 00:00:00|  2018-02-21 20:42:00|2017-02-05 01:32:00|           74.9|        null|        30061680|     2362181520|             null|
|     4101|       74|     M|    other|african_american|1937-01-14 00:00:00|  16.1|1997-04-10 00:00:00|       null|2012-03-30 00:00:00|               null|               null|               null|      5|          null|               null|        null|               null|                     1|  2011-08-25 00:00:00|                 null|  2011-08-25 00:00:00|2011-08-25 00:00:00|          74.66|        null|            null|     2354479200|             null|
|     5803|       89|     F|    other|           white|1924-03-06 00:00:00|  7.37|2013-06-05 00:00:00|       null|               null|               null|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-02-22 00:00:00|  2013-05-14 00:00:00|  2013-05-14 00:00:00|2013-02-22 00:00:00|          89.03|        null|         6994800|     2807564400|             null|
|     6654|       76|     F|    other|african_american|1939-04-08 00:00:00| 18.72|2015-07-08 00:00:00|       null|               null|               null|               null|2017-04-10 00:00:00|      4|          null|               null|        null|               null|                     1|  2017-04-10 00:00:00|                 null|  2017-04-10 00:00:00|2017-04-10 00:00:00|          78.06|        null|            null|     2461701600|             null|
|    12046|       48|     F|    other|           white|1957-01-03 00:00:00|  8.77|2005-04-02 00:00:00|       null|2007-08-03 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|     31|          null|               null|        null|               null|                     1|  2012-12-24 00:00:00|  2013-11-09 00:00:00|  2013-11-09 00:00:00|2012-12-24 00:00:00|          56.01|        null|        27648000|     1766361600|             null|
|    12799|       63|     F|    other|           other|1940-05-22 00:00:00| 21.93|2003-10-25 00:00:00|       null|               null|               null|               null|2009-03-04 00:00:00|     13|             1|2013-01-05 00:00:00|        null|2013-01-05 00:00:00|                     3|  2012-12-17 00:00:00|  2012-12-19 00:00:00|  2014-06-14 00:00:00|2012-12-17 00:00:00|          72.62|        null|          172800|     2290201200|6279021.369863014|
|    13289|       31|     M|    other|           white|1980-10-05 00:00:00| 16.41|2011-12-18 00:00:00|       null|               null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2004-09-07 00:00:00|                 null|  2004-09-07 00:00:00|2004-09-07 00:00:00|          23.94|        null|            null|      754963200|             null|
|    13623|       77|     M|    other|           white|1939-10-11 00:00:00|  null|               null|       null|               null|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|     22|          null|               null|        null|               null|                     1|  2017-10-15 00:00:00|  2017-10-15 00:01:00|  2018-06-01 00:00:00|2017-10-15 00:00:00|          78.07|        null|              60|     2461874400|             null|
|    13840|       42|     F|    other|           white|1967-02-08 00:00:00|  null|2009-04-27 00:00:00|       null|               null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|   null|          null|               null|        null|               null|                     1|  2015-02-07 00:00:00|                 null|  2015-02-07 00:00:00|2015-02-07 00:00:00|          48.03|        null|            null|     1514678400|             null|
|    15727|       58|     M|    other|           white|1951-01-07 00:00:00|  null|2004-11-01 00:00:00|       null|2008-03-19 00:00:00|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|      6|          null|               null|        null|               null|                     1|  2010-07-07 00:00:00|                 null|  2010-07-07 00:00:00|2010-07-07 00:00:00|          59.54|        null|            null|     1877551200|             null|
|    20683|       50|     F|    other|           other|1954-08-27 00:00:00| 17.67|2004-11-13 00:00:00|       null|               null|2001-03-06 00:00:00|               null|               null|      3|          null|               null|        null|               null|                     2|  2011-12-05 00:00:00|  2012-01-09 00:00:00|  2012-02-17 00:00:00|2011-12-05 00:00:00|          57.31|        null|         3024000|     1807401600|             null|
|    20735|       87|     F|    other|           white|1925-05-11 00:00:00|  5.13|2012-08-11 00:00:00|       null|               null|2012-08-11 00:00:00|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-09-24 00:00:00|  2013-10-01 00:00:00|  2015-11-01 00:00:00|2013-09-24 00:00:00|          88.43|        null|          604800|     2788812000|             null|
|    24171|       75|     F|    other|           white|1936-03-01 00:00:00| 18.13|2001-03-14 00:00:00|       null|               null|2004-01-20 00:00:00|               null|               null|      2|          null|               null|        null|               null|                     1|  2013-07-20 00:00:00|  2013-09-07 00:00:00|  2013-11-02 00:00:00|2013-07-20 00:00:00|          77.44|        null|         4233600|     2442088800|             null|
|    24347|       60|     F|    other|           other|1949-05-14 00:00:00| 10.42|2007-04-08 00:00:00|       null|2008-05-03 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|     11|          null|               null|        null|               null|                     1|  2010-09-07 00:00:00|  2010-11-16 00:00:00|  2010-11-16 00:00:00|2010-09-07 00:00:00|          61.36|        null|         6051600|     1935010800|             null|
|    28577|       69|     F|    other|african_american|1942-08-20 00:00:00|  null|               null|       null|               null|2011-03-23 00:00:00|               null|               null|     26|          null|               null|        null|               null|                     1|  2011-08-01 00:00:00|  2011-10-24 00:00:00|  2013-09-23 00:00:00|2011-08-01 00:00:00|          68.99|        null|         7257600|     2175807600|             null|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+---------------+-----------------+
only showing top 20 rows

In [51]:
df.select("Age_AD_Diag").show()

+-----------------+
|      Age_AD_Diag|
+-----------------+
|             null|
|8345510.136986301|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
|6279021.369863014|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
|             null|
+-----------------+
only showing top 20 rows

In [53]:
df.filter("Age_AD_Diag is not NULL").count()

5340

In [54]:
df.filter("Age_AD_Diag is NULL").count()

45052

In [42]:
#age of AD with Dementia diagnosed
YearDiff = (unix_timestamp('F_AlzDementia_DiagDay', "yyyy-MM-dd HH:mm:ss") - unix_timestamp('BIRTH_DATE', "yyyy-MM-dd HH:mm:ss"))
df = df.withColumn("Age_AD_Dem_Diag", YearDiff)
df.show()

+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+---------------+
|person_id|INDEX_AGE|GENDER|ETHNICITY|            RACE|         BIRTH_DATE|diagRL|         F_T2D_Diag|F_GEST_Diag|         F_T1D_Diag|         F_CVD_Diag|          F_LD_Diag|          F_KD_Diag|HBA1Cct|Ct_AlzDiagCode|       F_AlzDiagDay|S_AlzDiagDay|       L_AlzDiagDay|Ct_AlzDementiaDiagCode|F_AlzDementia_DiagDay|S_AlzDementia_DiagDay|L_AlzDementia_DiagDay|       F_Neuro_Diag|F_NeuroDiag_Age|Year_AD_Diag|Year_AD_Dem_Diag|Age_AD_Dem_Diag|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+---------------+
|     1238|       53|     F|    other|african_american|1950-10-06 00:00:00| 22.41|2001-04-07 00:00:00|       null|               null|               null|               null|1996-12-11 00:00:00|   null|          null|               null|        null|               null|                     1|  2017-04-14 00:00:00|                 null|  2017-04-14 00:00:00|2017-04-14 00:00:00|          66.57|        null|            null|     2099253600|
|     1342|       89|     F|    other|african_american|1920-04-19 00:00:00| 20.55|1997-11-03 00:00:00|       null|2001-04-03 00:00:00|1996-11-17 00:00:00|               null|               null|   null|             1|2016-10-28 00:00:00|        null|2016-10-28 00:00:00|                     2|  2011-06-25 00:00:00|  2012-05-06 00:00:00|  2016-10-28 00:00:00|2011-06-25 00:00:00|          91.24|        null|        27302400|     2877458400|
|     1645|       82|     M|    other|african_american|1928-05-07 00:00:00| 11.94|1999-12-21 00:00:00|       null|2010-12-04 00:00:00|2011-11-02 00:00:00|               null|2011-11-12 00:00:00|      7|          null|               null|        null|               null|                     1|  2011-07-13 00:00:00|  2011-07-15 00:00:00|  2011-07-15 00:00:00|2011-07-13 00:00:00|          83.24|        null|          172800|     2624997600|
|     2366|       60|     F|    other|african_american|1948-10-29 00:00:00| 13.33|1996-06-19 00:00:00|       null|1999-06-03 00:00:00|2009-06-10 00:00:00|               null|2009-05-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2009-09-12 00:00:00|                 null|  2009-09-12 00:00:00|2009-09-12 00:00:00|          60.91|        null|            null|     1920924000|
|     2659|       82|     M|    other|           white|1926-12-31 00:00:00| 15.55|2003-04-23 00:00:00|       null|               null|2009-06-27 00:00:00|               null|2012-03-16 00:00:00|      1|          null|               null|        null|               null|                     2|  2012-03-16 00:00:00|  2012-03-30 00:00:00|  2012-12-18 00:00:00|2012-03-16 00:00:00|          85.27|        null|         1209600|     2688933600|
|     3918|       68|     F|    other|african_american|1942-03-31 00:00:00|  null|               null|       null|               null|               null|               null|               null|     13|          null|               null|        null|               null|                     1|  2017-02-05 01:32:00|  2018-01-19 00:00:00|  2018-02-21 20:42:00|2017-02-05 01:32:00|           74.9|        null|        30061680|     2362181520|
|     4101|       74|     M|    other|african_american|1937-01-14 00:00:00|  16.1|1997-04-10 00:00:00|       null|2012-03-30 00:00:00|               null|               null|               null|      5|          null|               null|        null|               null|                     1|  2011-08-25 00:00:00|                 null|  2011-08-25 00:00:00|2011-08-25 00:00:00|          74.66|        null|            null|     2354479200|
|     5803|       89|     F|    other|           white|1924-03-06 00:00:00|  7.37|2013-06-05 00:00:00|       null|               null|               null|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-02-22 00:00:00|  2013-05-14 00:00:00|  2013-05-14 00:00:00|2013-02-22 00:00:00|          89.03|        null|         6994800|     2807564400|
|     6654|       76|     F|    other|african_american|1939-04-08 00:00:00| 18.72|2015-07-08 00:00:00|       null|               null|               null|               null|2017-04-10 00:00:00|      4|          null|               null|        null|               null|                     1|  2017-04-10 00:00:00|                 null|  2017-04-10 00:00:00|2017-04-10 00:00:00|          78.06|        null|            null|     2461701600|
|    12046|       48|     F|    other|           white|1957-01-03 00:00:00|  8.77|2005-04-02 00:00:00|       null|2007-08-03 00:00:00|2013-09-27 00:00:00|               null|2005-03-08 00:00:00|     31|          null|               null|        null|               null|                     1|  2012-12-24 00:00:00|  2013-11-09 00:00:00|  2013-11-09 00:00:00|2012-12-24 00:00:00|          56.01|        null|        27648000|     1766361600|
|    12799|       63|     F|    other|           other|1940-05-22 00:00:00| 21.93|2003-10-25 00:00:00|       null|               null|               null|               null|2009-03-04 00:00:00|     13|             1|2013-01-05 00:00:00|        null|2013-01-05 00:00:00|                     3|  2012-12-17 00:00:00|  2012-12-19 00:00:00|  2014-06-14 00:00:00|2012-12-17 00:00:00|          72.62|        null|          172800|     2290201200|
|    13289|       31|     M|    other|           white|1980-10-05 00:00:00| 16.41|2011-12-18 00:00:00|       null|               null|2003-05-05 00:00:00|2011-10-25 00:00:00|2014-01-03 00:00:00|      2|          null|               null|        null|               null|                     1|  2004-09-07 00:00:00|                 null|  2004-09-07 00:00:00|2004-09-07 00:00:00|          23.94|        null|            null|      754963200|
|    13623|       77|     M|    other|           white|1939-10-11 00:00:00|  null|               null|       null|               null|2010-12-29 00:00:00|               null|2016-06-30 00:01:00|     22|          null|               null|        null|               null|                     1|  2017-10-15 00:00:00|  2017-10-15 00:01:00|  2018-06-01 00:00:00|2017-10-15 00:00:00|          78.07|        null|              60|     2461874400|
|    13840|       42|     F|    other|           white|1967-02-08 00:00:00|  null|2009-04-27 00:00:00|       null|               null|2009-03-13 00:00:00|2014-12-20 00:00:00|2015-04-18 00:00:00|   null|          null|               null|        null|               null|                     1|  2015-02-07 00:00:00|                 null|  2015-02-07 00:00:00|2015-02-07 00:00:00|          48.03|        null|            null|     1514678400|
|    15727|       58|     M|    other|           white|1951-01-07 00:00:00|  null|2004-11-01 00:00:00|       null|2008-03-19 00:00:00|2010-07-09 00:00:00|               null|2013-07-02 00:00:00|      6|          null|               null|        null|               null|                     1|  2010-07-07 00:00:00|                 null|  2010-07-07 00:00:00|2010-07-07 00:00:00|          59.54|        null|            null|     1877551200|
|    20683|       50|     F|    other|           other|1954-08-27 00:00:00| 17.67|2004-11-13 00:00:00|       null|               null|2001-03-06 00:00:00|               null|               null|      3|          null|               null|        null|               null|                     2|  2011-12-05 00:00:00|  2012-01-09 00:00:00|  2012-02-17 00:00:00|2011-12-05 00:00:00|          57.31|        null|         3024000|     1807401600|
|    20735|       87|     F|    other|           white|1925-05-11 00:00:00|  5.13|2012-08-11 00:00:00|       null|               null|2012-08-11 00:00:00|               null|               null|   null|          null|               null|        null|               null|                     1|  2013-09-24 00:00:00|  2013-10-01 00:00:00|  2015-11-01 00:00:00|2013-09-24 00:00:00|          88.43|        null|          604800|     2788812000|
|    24171|       75|     F|    other|           white|1936-03-01 00:00:00| 18.13|2001-03-14 00:00:00|       null|               null|2004-01-20 00:00:00|               null|               null|      2|          null|               null|        null|               null|                     1|  2013-07-20 00:00:00|  2013-09-07 00:00:00|  2013-11-02 00:00:00|2013-07-20 00:00:00|          77.44|        null|         4233600|     2442088800|
|    24347|       60|     F|    other|           other|1949-05-14 00:00:00| 10.42|2007-04-08 00:00:00|       null|2008-05-03 00:00:00|2007-04-08 00:00:00|               null|2010-06-28 00:00:00|     11|          null|               null|        null|               null|                     1|  2010-09-07 00:00:00|  2010-11-16 00:00:00|  2010-11-16 00:00:00|2010-09-07 00:00:00|          61.36|        null|         6051600|     1935010800|
|    28577|       69|     F|    other|african_american|1942-08-20 00:00:00|  null|               null|       null|               null|2011-03-23 00:00:00|               null|               null|     26|          null|               null|        null|               null|                     1|  2011-08-01 00:00:00|  2011-10-24 00:00:00|  2013-09-23 00:00:00|2011-08-01 00:00:00|          68.99|        null|         7257600|     2175807600|
+---------+---------+------+---------+----------------+-------------------+------+-------------------+-----------+-------------------+-------------------+-------------------+-------------------+-------+--------------+-------------------+------------+-------------------+----------------------+---------------------+---------------------+---------------------+-------------------+---------------+------------+----------------+---------------+
only showing top 20 rows

In [44]:
df.select("Age_AD_Dem_Diag").show()

+---------------+
|Age_AD_Dem_Diag|
+---------------+
|     2099253600|
|     2877458400|
|     2624997600|
|     1920924000|
|     2688933600|
|     2362181520|
|     2354479200|
|     2807564400|
|     2461701600|
|     1766361600|
|     2290201200|
|      754963200|
|     2461874400|
|     1514678400|
|     1877551200|
|     1807401600|
|     2788812000|
|     2442088800|
|     1935010800|
|     2175807600|
+---------------+
only showing top 20 rows

In [56]:
df.filter("Age_AD_Dem_Diag is not NULL").count()

49482

In [57]:
df.filter("Age_AD_Dem_Diag is NULL").count()

910

In [38]:
df.columns

['person_id',
 'INDEX_AGE',
 'GENDER',
 'ETHNICITY',
 'RACE',
 'BIRTH_DATE',
 'diagRL',
 'F_T2D_Diag',
 'F_GEST_Diag',
 'F_T1D_Diag',
 'F_CVD_Diag',
 'F_LD_Diag',
 'F_KD_Diag',
 'HBA1Cct',
 'Ct_AlzDiagCode',
 'F_AlzDiagDay',
 'S_AlzDiagDay',
 'L_AlzDiagDay',
 'Ct_AlzDementiaDiagCode',
 'F_AlzDementia_DiagDay',
 'S_AlzDementia_DiagDay',
 'L_AlzDementia_DiagDay',
 'F_Neuro_Diag',
 'F_NeuroDiag_Age',
 'Year_AD_Diag',
 'Year_AD_Dem_Diag']

In [40]:
df.select('Year_AD_Diag','Year_AD_Dem_Diag').show()

+------------+----------------+
|Year_AD_Diag|Year_AD_Dem_Diag|
+------------+----------------+
|        null|            null|
|        null|        27302400|
|        null|          172800|
|        null|            null|
|        null|         1209600|
|        null|        30061680|
|        null|            null|
|        null|         6994800|
|        null|            null|
|        null|        27648000|
|        null|          172800|
|        null|            null|
|        null|              60|
|        null|            null|
|        null|            null|
|        null|         3024000|
|        null|          604800|
|        null|         4233600|
|        null|         6051600|
|        null|         7257600|
+------------+----------------+
only showing top 20 rows